config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations'}
  
  authenticated :user do
    root to: 'users#index', as: :authenticated_root
  end
  root to: redirect('/users/sign_in')

  resources :users
  resources :kinds
  resources :categories
  resources :cash_flows

end

app/models/cash_flow.rb
class CashFlow < ActiveRecord::Base
	belongs_to :user
	belongs_to :kind

	validates :value, presence: true, numericality: { less_than: 10000000, greater_than: -10000000 }
	validates :date, presence: true
	validates :user_id, presence: true
	validates :kind_id, presence:true

end

app/controllers/cash_flows_controller.rb
class CashFlowsController < ApplicationController
	before_action :set_cash_flow, only: [:show, :edit, :update, :destroy]
    
	def index
		# @user_cash_flow = CashFlow.where(user_id: session[:user_id])
		@cash_flows = CashFlow.all.order(:date)
		@default_kinds = Kind.where(default: true)
		@cat_1_sum = Kind.where(category_id: 1)
	end

	def show
	end

	def new
	  @cash_flow = CashFlow.new	
	end

	def cash_flows_params
		params.require(:cash_flow).permit(:description, :value, :date, :kind_id, :user_id)
	end

	def create
		@cash_flow = CashFlow.new(cash_flows_params)
		# @cash_flow.user_id = session[:user_id]

		if @cash_flow.save
			redirect_to cash_flows_path, notice: "#{@cash_flow.description} lançado com sucesso!"
		else
			render "new"
		end
	end

	def edit
	end

	def update
		if @cash_flow.update_attributes(cash_flows_params)
			redirect_to cash_flows_path, notice: "#{@cash_flow.description} atualizado com sucesso!"
		else
			render "edit"
		end
	end

	def destroy
		@cash_flow.destroy
		respond_to do |format|
      format.html { redirect_to cash_flows_url, notice: "#{@cash_flow.description} removido com sucesso!" }
      format.json { head :no_content }
    end
	end

  private
	  def set_cash_flow
		  @cash_flow = CashFlow.find(params[:id])
  	end
end

app/helpers/cash_flows_helper.rb
module CashFlowsHelper
  def category_options
    Category.all.name.to_a.map do |name|
      "#{name}"
    end
  end
end

app/views/cash_flows/_form.html.erb
<%= form_for @cash_flow do |f| %>
  <% if @cash_flow.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <% @cash_flow.errors.full_messages.each do |msg| %>
        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
        <span class="sr-only">Error:</span>
        <%= msg %><br/>
      <% end %>
    </div>        
  <% end %>

  <div class="row">
    <div class="col-xs-6 col-md-2">
      <div class="form-group">
        <%= f.label :date %>
        <%= f.date_field :date, value: Date.today, class: "form-control input-sm" %>
      </div>
    </div>
   
    <div class="col-xs-6 col-md-2">
      <div class="form-group">
        <%= f.label :kind_id %>
        <%= params[:category] %>
        <%= f.collection_select(:kind_id, Kind.where(default: true), :id, :name, 
                                                {}, class: "form-control input-sm") %>
      </div>
    </div>
    <div class="col-xs-6 col-md-2">
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_field :description, class: "form-control input-sm" %>
      </div>
    </div>
    <div class="col-xs-6 col-md-1">
      <div class="form-group">
        <%= f.label :value %>
        <%= f.number_field :value, step: 0.01, class: "form-control input-sm" %>
      </div>
    </div>
    <%= f.submit "Salvar", class: "btn btn-primary" %>
  </div>
<% end %>

      

app/views/cash_flows/edit.html.erb
<h1>Editar <%= @cash_flow.description %></h1>

<%= render "form" %>

app/views/cash_flows/index.html.erb
<div class="row">
	<div class="col-md-4">
		<%= select_month Date.today, class: "form-control" %>
		<%= select_year Date.today %>
	</div>
	<div class="col-md-8">
	</div>
</div>

<table class="table table-striped">
	<thead>
		<tr>
			<th>
				Data
			</th>
			<th>
				Tipo
			</th>
		  <th>
				Descrição
			</th>
			<th>
				Valor
			</th>
			<th>
      </th>	
		</tr>
	</thead>
	<tbody>
	  <%# @user_cash_flow.each do |cash_flow| %>
	  <tr>
	  	<td>
	  		<%# cash_flow.date %>
	  	</td>
	  	<td>
	  		<%# Kind.find(cash_flow.kind_id).name %>
	  	</td>
      <td>
	  		<%# cash_flow.description %>
	  	</td>
	  	<td>
	  		<%# number_to_currency(cash_flow.value) %>
	  	</td>
	  	<td> 
	  		<div class="btn-group btn-group-sm">
	  	  <%# link_to edit_cash_flow_path(cash_flow), class: "btn btn-default" do %>
	  	  	<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
	  	  <% end %> 
          <%# link_to cash_flow, method: :delete, data: { confirm: 
          	"Você tem certeza que quer remover #{cash_flow.description}?" }, class: "btn btn-default" do %>		
	  				<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
	  			<%# end %>
	  		</div>
	  	</td>
	  	<%# end %>
	  </tr>
	</tbody>

</table>

<%# link_to "Registrar nova Entrada / Despesa", new_cash_flow_path %>

app/views/cash_flows/new.html.erb
<%= render "form" %>