config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations'}
  
  authenticated :user do
    root to: 'users#index', as: :authenticated_root
  end
  root to: redirect('/users/sign_in')

  resources :users
  resources :kinds
  resources :categories
  resources :cash_flows

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rosso - Focolare</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <%= link_to "Rosso", root_path, class: "navbar-brand" %>
      <ul class="nav navbar-nav">
      </ul>
    </div>
    
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="navbar-text"><span class="glyphicon glyphicon-user"></span>
            <%= current_user.name %>
          </li> 
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" 
                          aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-cog"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Popos", users_path %></li>
              <li><%= link_to "Tipos", kinds_path %></li>
              <li><%= link_to "Categorias", categories_path %></li>
              <li><%= link_to "Lançamento Entradas / Despesas", cash_flows_path %></li>           
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<div class="container-fluid">


    <% if flash[:notice] %>
      <div class="notice">
        <%= flash[:notice] %>
      </div>
    <% end -%>

    <% if flash[:alert] %>
      <div class="alert">
        <%= flash[:alert] %>
      </div>
    <% end -%>
  
  <%= yield %>
</div>
</body>
</html>